<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <link rel="stylesheet" href="<?php echo $this->css ?>" type="text/css">
    <script src="<?php echo $this->playerhtml5_js ?>" type="text/javascript"></script>
    <!-- get rid of jquery (PRO accelerated loading CONS drop i18n intenalization)
    script src="<?php echo $this->jquery ?>" type="text/javascript"></script>
    <script src="<?php echo $this->jquery_i18n ?>" type="text/javascript"></script-->
    <script src="/locale/general-translation-table" type="text/javascript"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

 <script src="https://cdn.jsdelivr.net/npm/hls.js@1"></script>
     <script type="text/javascript"  type=module >
        //$.i18n.setDictionary(general_dict);

        var MAX_MOBILE_SCREEN_WIDTH = 760;

        var Html5Player = function() {
            var id_element = getRandomIdPlayer(3000);
            this.mobileDetect = this.mobileDetect();
            this.playerMode = "<?php echo $this->playerMode ?>";
            this.settings = {
                'elementId': id_element, // leave alone
                'autoplay': false, // or true (only works on some browsers)
                'forceHTTPS': false, // or true if the stream is in SSL (beware of the listening port, usually 8000)
                'replacePort': false, // false for disabled or '8000' as the usual start port, forces to specify replacePortTo.
                'replacePortTo': '' // either '' to use the default port of the browser (80/http, 443/https) or '8443' to force the port of the stream.
            };

            if (this.playerMode == "manual") {
                this.settings.url = <?php echo $this->streamURL ?>;
                this.settings.codec = "<?php echo $this->codec ?>";
            } else if (this.playerMode == "file") {
                this.settings.url = <?php echo $this->streamURL ?>;
                this.settings.codec = "<?php echo $this->codec ?>";
            } else if (this.playerMode == "auto") {
                this.availableMobileStreamQueue = <?php echo $this->availableMobileStreams ?>;
                this.availableDesktopStreamQueue = <?php echo $this->availableDesktopStreams ?>;
                var stream = this.getNextAvailableStream();
                this.settings.url = stream["url"];
                this.settings.codec = stream["codec"];
            }
//this.settings.url="http://localhost:80/hls/main";
            // Create the Muses player object
            playerhtml5_insert(this.settings);
            playerhtml5_audio = document.getElementById(id_element);
            if (playerhtml5_audio.played == true) togglePlayStopButton();

            // Configure player title
            var player_title = <?php echo $this->player_title ?>;
            if (player_title === null) {
                ///TODO without JQuery
                //$(".airtime_header").hide();
                //$(".airtime_player").css('height', '150px');
            } else {
                //$("p.station_name").html(player_title);
                document.getElementById('station_name').textContent=player_title;
            }

            attachStreamMetadataToPlayer();

            // detects events in HTML5 mode

        };
        Html5Player.prototype.mobileDetect = function() {
            return (screen.width <= MAX_MOBILE_SCREEN_WIDTH);
        }

        // This function is called if an error occurs while a client is
        // attempting to connect to a stream (An error would occur if
        // the streams listener count has been maxed out or if the stream is down).
        // It checks if the client is a mobile device or not and returns the next
        // best available stream.
        Html5Player.prototype.getNextAvailableStream = function() {
            if (this.mobileDetect && this.availableMobileStreamQueue.length > 0) {
                return this.getNextAvailableMobileStream();
            }

            if (!this.mobileDetect && this.availableDesktopStreamQueue.length > 0) {
                return this.getNextAvailableDesktopStream();
            }

            // If we get to this point there are no available streams for the
            // type of device the client has connected with so just return
            // the next available stream - first we'll try the desktop streams
            var desktopStream = this.getNextAvailableDesktopStream();
            if (desktopStream) {
                return desktopStream;
            } else {
                return this.getNextAvailableMobileStream();
            }

        }

        // Gets and returns the next available mobile stream from the queue,
        // but adds it back to the end of the queue to be recycled.
        Html5Player.prototype.getNextAvailableMobileStream = function() {
            var stream = this.availableMobileStreamQueue.shift();
            //add to end of queue
            this.availableMobileStreamQueue.push(stream);
            return stream;
        }

        // Gets and returns the next available desktop stream from the queue,
        // but adds it back to the end of the queue to be recycled.
        Html5Player.prototype.getNextAvailableDesktopStream = function() {
            var stream = this.availableDesktopStreamQueue.shift();
            //add to end of queue
            this.availableDesktopStreamQueue.push(stream);
            return stream;
        }

        Html5Player.prototype.play = function() {
            console.log('play');
            //playerhtml5_audio.src = this.settings.url;
            playerhtml5_audio.play();
            togglePlayStopButton();
        };

        Html5Player.prototype.stop = function() {
            console.log('stop');
            playerhtml5_audio.pause();
            togglePlayStopButton();
        };

        function togglePlayStopButton() {
            document.getElementById("play_button").classList.toggle("hide_button");
            document.getElementById("stop_button").classList.toggle("hide_button");
        }


        window.onload=function(){
            let playbuts=document.getElementsByClassName('play');
            playbuts[0].onClick=function(){

                if (playbuts[0].hasClass("pause"))
                    html5Player.stop();
                else
                    html5Player.play();
                playbuts[0].classList.toggle("pause");
            };
        }
        /*$(document).ready(function() {
            $(".play").click(function() {
                if ($(this).hasClass("pause")) {
                    html5Player.stop();
                } else {
                    html5Player.play();
                }

                $(this).toggleClass("pause");
            });
        });*/

        // variables for updating the player's metadata
        var time_to_next_track_starts = 0;
        var metadataTimer = null;
        var current_track_end_time;var current_track_start_time;
        function fillNodeArray( arr,content){
	   //for(let i=0;i<arr.length;++i) arr[i].innerHTML=content;
	  Array.prototype.filter.call(
	  arr,
	  function (elmt) {
	       elmt.innerHTML=content;
	       console.log(content);
	  },
	);
	};
        // Fetches the streams metadata from the Airtime live-info API
        // and attaches it to the player UI.
        //
        // The metadata is fetched when the current track is about to end.
        function attachStreamMetadataToPlayer() {

            let metadataxhr = new XMLHttpRequest();
            metadataxhr.open('GET', "<?php echo $this->metadata_api_url ?>");
            metadataxhr.onload = function() {
                    if (metadataxhr.status != 200) { metadataxhr.onerror();return;}

                    let data=JSON.parse(this.response);
                    var nowdivs=document.getElementsByClassName('now_playing');
		    var rcursor=document.getElementById("radio_cursor");
                    if (data.current === null) {
                        if (data.currentShow != null && data.currentShow.length > 0) {
                            //Master/show source have no current track but they do have a current show.
                            //$("div.now_playing").html($.i18n._("On Air") + "<span>" + data.currentShow[0].name + "</span>");
                            fillNodeArray(nowdivs,"On Air" + "<span>" + data.currentShow[0].name + "</span>");
                        } else {
                            //$("div.now_playing").html($.i18n._("Off Air") + "<span>" + $.i18n._("Offline") + "</span>");
                            fillNodeArray(nowdivs,"Off Air" + "<span>" + "Offline" + "</span>");
                        }
                        time_to_next_track_starts = 20000;
                    } else {

                        //console.log( data.current.name);
                        var artist = '';// data.current.name;//.split(" - ")[0];
                        var track =data.current.name;//.split(" - ")[1];
                        var nowPlayingHtml = "";
                        if (artist) {
                            nowPlayingHtml += artist+" - ";
                        }
                        if (track) {
                            nowPlayingHtml +=  track ;
                        }

                        //$("div.now_playing").html(nowPlayingHtml);
                        fillNodeArray(nowdivs,nowPlayingHtml);

                        current_track_end_time = new Date(data.current.ends);
                        var artwork_url=data.current.metadata.artwork_url;

                        artwork_url=artwork_url.replace('&amp;','&');
                        //$("#artwork_image").attr('src', artwork_url );
                        document.getElementById('artwork_image').src=artwork_url;

                        if (current_track_end_time == "Invalid Date" || isNaN(current_track_end_time)) {
                            // If the conversion didn't work (since the String is not in ISO format)
                            // then change it to be ISO-compliant. This is somewhat hacky and may break
                            // if the date string format in live-info changes!
                            current_track_end_time = new Date((data.current.ends).replace(" ", "T"));
                        }
                        var current_time = new Date();
                        //convert current_time to UTC to match the timezone of time_to_next_track_starts
                        current_time = new Date(current_time.getTime() + current_time.getTimezoneOffset() * 60 * 1000);
                        current_track_start_time= new Date((data.current.starts).replace(" ", "T"));
                        time_to_next_track_starts = current_track_end_time - current_time;
                       }


                    let schedule_list=document.getElementsByClassName('schedule_list');
                    if (data.next === null) {
                        //$("ul.schedule_list").find("li").html($.i18n._("Nothing scheduled"));
                        schedule_list[0].children[0].innerHTML="Nothing scheduled";
                    } else {
                        //$("ul.schedule_list").find("li").html(data.next.name);
                        schedule_list[0].children[0].innerHTML=data.next.name;

                    }


                 //Preventative code if the local and remote clocks are out of sync.
            if (isNaN(time_to_next_track_starts) || time_to_next_track_starts < 0) {
                time_to_next_track_starts = 0;
            }


		var current_time = new Date();
		var metadelay = self.html5Player.settings.codec == 'hls' ? 8000 : 0; //timeoffset  hls stream is 8s late on calendar
		var current_time = new Date(current_time.getTime() - metadelay+
		 current_time.getTimezoneOffset() * 60 * 1000);

		/*if (current_track_end_time === undefined )
			time_to_next_track_starts=0;
		else*/
			time_to_next_track_starts = current_track_end_time - current_time;


		var cursor_ratio=rcursor.clientWidth/rcursor.parentNode.clientWidth; ///cursor size in perc of its parent
		var time_from_start_time= (current_time-current_track_start_time ) /(current_track_end_time-current_track_start_time);
		console.log(time_from_start_time);//hoping perc
		//time_from_start_time=0;
		time_from_start_time=time_from_start_time*(1.0-cursor_ratio);
		var transl=(1.0-cursor_ratio)/cursor_ratio;
		console.log(transl);//hoping perc


		 // $("#radio_cursor").attr('style', cursor_transition );
		console.log('current_track_end_time'+current_track_end_time);
		console.log('current_time'+current_time);
		console.log('time_to_next_track_starts'+time_to_next_track_starts/1000);


		const cursoranimate = [
		{ transform: "translate("+(time_from_start_time*100/cursor_ratio)+"%) " },
		{ transform: "translate("+transl*100+"%) " },
		];
		const cursoranimateTiming = {
		duration: Math.max(time_to_next_track_starts,0) ,
		iterations: 1,
		};
		console.log(rcursor.clientWidth/rcursor.parentNode.clientWidth);
		rcursor.animate(cursoranimate, cursoranimateTiming);

		metadataTimer= setTimeout(attachStreamMetadataToPlayer,time_to_next_track_starts+ 3000);




                }

                /*function() {
  if (metadataxhr.status != 200) { // analyse l'état HTTP de la réponse
    alert(`Error ${metadataxhr.status}: ${metadataxhr.statusText}`); // e.g. 404: Not Found
  } else { // show the result
    alert(`Done, got ${metadataxhr.response.length} bytes`); // response est la réponse du serveur
  }
};*/
//metadataxhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");

metadataxhr.onerror = function() {
  console.log("Metadata request failed, relaunching in 5 sec");
  metadataTimer= setTimeout(attachStreamMetadataToPlayer, 5000);
};
metadataxhr.send( );

            /*$.ajax({
                url: "/api/live-info",
                data: {
                    type: "interval",
                    limit: "5"
                },
                dataType: "jsonp",
                success: function(data) {

                    if (data.current === null) {
                        if (data.currentShow != null && data.currentShow.length > 0) {
                            //Master/show source have no current track but they do have a current show.
                            $("p.now_playing").html($.i18n._("On Air") + "<span>" + data.currentShow[0].name + "</span>");
                        } else {
                            $("p.now_playing").html($.i18n._("Off Air") + "<span>" + $.i18n._("Offline") + "</span>");
                        }
                        time_to_next_track_starts = 20000;
                    } else {

                        console.log( data.current.name);
                        var artist = '';// data.current.name;//.split(" - ")[0];
                        var track =data.current.name;//.split(" - ")[1];
                        var nowPlayingHtml = "";
                        if (artist) {
                            nowPlayingHtml += artist+" - ";
                        }
                        if (track) {
                            nowPlayingHtml +=  track ;
                        }
                        console.log(nowPlayingHtml);
                        $("div.now_playing").html(nowPlayingHtml);

                        current_track_end_time = new Date(data.current.ends);
                        var artwork_url=data.current.metadata.artwork_url;

                        artwork_url=artwork_url.replace('&amp;','&');
                        //artwork_url='https://deltacast.hd.free.fr/api/track?id=26&return=artwork';
                        $("#artwork_image").attr('src', artwork_url );
                        if (current_track_end_time == "Invalid Date" || isNaN(current_track_end_time)) {
                            // If the conversion didn't work (since the String is not in ISO format)
                            // then change it to be ISO-compliant. This is somewhat hacky and may break
                            // if the date string format in live-info changes!
                            current_track_end_time = new Date((data.current.ends).replace(" ", "T"));
                        }
                        var current_time = new Date();
                        //convert current_time to UTC to match the timezone of time_to_next_track_starts
                        current_time = new Date(current_time.getTime() + current_time.getTimezoneOffset() * 60 * 1000);
                        current_track_start_time= new Date((data.current.starts).replace(" ", "T"));
                        time_to_next_track_starts = current_track_end_time - current_time;
                       }

                    if (data.next === null) {
                        $("ul.schedule_list").find("li").html($.i18n._("Nothing scheduled"));
                    } else {
                        $("ul.schedule_list").find("li").html(data.next.name);
                    }
                }
            });
             //Preventative code if the local and remote clocks are out of sync.
            if (isNaN(time_to_next_track_starts) || time_to_next_track_starts < 0) {
                time_to_next_track_starts = 0;
            }


		var current_time = new Date();
		var current_time = new Date(current_time.getTime() + current_time.getTimezoneOffset() * 60 * 1000);

		/*if (current_track_end_time === undefined )
			time_to_next_track_starts=0;
		else* /
			time_to_next_track_starts = current_track_end_time - current_time;
		var time_from_start_time= (current_time-current_track_start_time ) /(current_track_end_time-current_track_start_time);
		console.log(time_from_start_time);//hoping perc
		var cursor_ratio=3; ///cursor size in perc of its parent
		var transl=(100*(100-cursor_ratio))/cursor_ratio;
		console.log(transl);//hoping perc
		transl=transl-(time_from_start_time)*100*(100-cursor_ratio)/cursor_ratio;
		console.log(transl);//hoping perc
		//transl=0;
		var cursor_transition="position:relative;left:"+time_from_start_time*100+"%;height: 100%;width: "+cursor_ratio+"%; transform: translate("+transl+"%);background-color: #787878;opacity:0.5;display: block;transition: transform linear "+time_to_next_track_starts/1000+"s;  ";

		 // $("#radio_cursor").attr('style', cursor_transition );
		console.log('current_track_end_time'+current_track_end_time);
		console.log('current_time'+current_time);
		console.log('time_to_next_track_starts'+time_to_next_track_starts/1000);
		document.getElementById("radio_cursor").style=  cursor_transition;
		// Add 3 seconds to the timeout so Airtime has time to update the metadata before we fetch it
		metadataTimer = null;
		metadataTimer= setTimeout(attachStreamMetadataToPlayer,time_to_next_track_starts+ 3000);
		 //Math.max(time_to_next_track_starts+ 3000,0) );
*/



        }
    </script>

    <style type="text/css">
        /*
        We have to have the default Muses skin displayed on the page or else
        the player will not work. Setting the display to none and hidden does
        not work. It has to be "visible" on the page. As a hacky work around we
        set the height and width to 1px so users will not see it.
        */
        #html5player_skin {
            width: 800;
            height: 800;
            overflow: hidden;
        }
        #time_bar{
            width:100%;
            overflow:hidden;
            height: 20px;
            //background-color:rgb(53,230,197);
            display:inline-block;
        }
        #radio_cursor
        {
            width:3%;
            position:relative;
            display: block;
            height: 100%;
            background-color: #787878;
            opacity:0.5;
        }
    </style>

</head>

<body>

    <div id="player" <?php if ($this->player_style == "basic") echo "style='display:block;'";
                        else echo "style='display:none'"; ?>>
        <div class="airtime_player">

            <div class="airtime_header">
                <p id="station_name">station_name</p>
            </div>

            <div class="airtime_box">
                <span id="artwork">
                <img  id="artwork_image" src="/css/images/maintenance.png"   onerror='this.src="/css/images/maintenance.png"' style="width: 50px;padding-left:15px;" ></img>
                </span>
                <div class="airtime_button">
                    <span id="play_button" class="play_button" onclick="html5Player.play()"></span>
                    <span id="stop_button" class="stop_button hide_button" onclick="html5Player.stop()"></span>
                </div>
                <div id="div_playing">
                <div class="now_playing" style></div>
                <div id="time_bar">  <div id="radio_cursor" > </div></div>
                </div>

            </div>

            <div style="clear:both"></div>

            <div class="airtime_schedule">
                <p class="airtime_next"><?php echo _("Next") ?></p>
                <ul class="schedule_list">
                    <li></li>
                </ul>
            </div>
            <a class="airtime_pro" target="_blank" href="<?php echo PRODUCT_SITE_URL; ?>"><?php printf(_('Powered by %s'), PRODUCT_NAME); ?></a>

        </div>
    </div>

    <div id="premium_player" <?php if ($this->player_style == "premium") echo "style='display:block;'";
                                else echo "style='display:none'"; ?>>
        <div class="bottom_bar">
            <div class="play cont_btn"></div>

            <div class="on_air">
                <div class="now_playing"></div>
            </div>
        </div>

    </div>

    <div id="html5player_skin">
        <script type="text/javascript">
        let decoder ;

function getTextDecoder() {
  if (!decoder && typeof self.TextDecoder !== 'undefined') {
    decoder = new self.TextDecoder('utf-8');
  }

  return decoder;
}
   function utf8ArrayToStr  (
  array ,
  exitOnNull  = false,
)  {
  const decoder = getTextDecoder();
  if (decoder) {
    const decoded = decoder.decode(array);

    if (exitOnNull) {
      // grab up to the first null
      const idx = decoded.indexOf('\0');
      return idx !== -1 ? decoded.substring(0, idx) : decoded;
    }

    // remove any null characters
    return decoded.replace(/\0/g, '');
  }

  const len = array.length;
  let c;
  let char2;
  let char3;
  let out = '';
  let i = 0;
  while (i < len) {
    c = array[i++];
    if (c === 0x00 && exitOnNull) {
      return out;
    } else if (c === 0x00 || c === 0x03) {
      // If the character is 3 (END_OF_TEXT) or 0 (NULL) then skip it
      continue;
    }
    switch (c >> 4) {
      case 0:
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
      case 6:
      case 7:
        // 0xxxxxxx
        out += String.fromCharCode(c);
        break;
      case 12:
      case 13:
        // 110x xxxx   10xx xxxx
        char2 = array[i++];
        out += String.fromCharCode(((c & 0x1f) << 6) | (char2 & 0x3f));
        break;
      case 14:
        // 1110 xxxx  10xx xxxx  10xx xxxx
        char2 = array[i++];
        char3 = array[i++];
        out += String.fromCharCode(
          ((c & 0x0f) << 12) | ((char2 & 0x3f) << 6) | ((char3 & 0x3f) << 0),
        );
        break;
      default:
    }
  }
  return out;
};

function decodeFrame  (frame){
  if (frame.type === 'PRIV') {
    return decodePrivFrame(frame);
  } else if (frame.type[0] === 'W') {
    return decodeURLFrame(frame);
  }

  return decodeTextFrame(frame);
};

function decodePrivFrame  (
  frame
) {
  /*
  Format: <text string>\0<binary data>
  */
  if (frame.size < 2) {
    return undefined;
  }

  const owner = utf8ArrayToStr(frame.data, true);
  const privateData = new Uint8Array(frame.data.subarray(owner.length + 1));

  return { key: frame.type, info: owner, data: privateData.buffer };
};

function decodeTextFrame  (frame) {
  if (frame.size < 2) {
    return undefined;
  }

  if (frame.type === 'TXXX') {
    /*
    Format:
    [0]   = {Text Encoding}
    [1-?] = {Description}\0{Value}
    */
    let index = 1;
    const description = utf8ArrayToStr(frame.data.subarray(index), true);

    index += description.length + 1;
    const value = utf8ArrayToStr(frame.data.subarray(index));

    return { key: frame.type, info: description, data: value };
  }
  /*
  Format:
  [0]   = {Text Encoding}
  [1-?] = {Value}
  */
  const text = utf8ArrayToStr(frame.data.subarray(1));
  return { key: frame.type, data: text };
};

function decodeURLFrame (frame) {
  if (frame.type === 'WXXX') {
    /*
    Format:
    [0]   = {Text Encoding}
    [1-?] = {Description}\0{URL}
    */
    if (frame.size < 2) {
      return undefined;
    }

    let index = 1;
    const description  = utf8ArrayToStr(
      frame.data.subarray(index),
      true,
    );

    index += description.length + 1;
    const value  = utf8ArrayToStr(frame.data.subarray(index));

    return { key: frame.type, info: description, data: value };
  }
  /*
  Format:
  [0-?] = {URL}
  */
  const url  = utf8ArrayToStr(frame.data);
  return { key: frame.type, data: url };
};

function readTimeStamp   (
  timeStampFrame
) {
  if (timeStampFrame.data.byteLength === 8) {
    const data = new Uint8Array(timeStampFrame.data);
    // timestamp is 33 bit expressed as a big-endian eight-octet number,
    // with the upper 31 bits set to zero.
    const pts33Bit = data[3] & 0x1;
    let timestamp =
      (data[4] << 23) + (data[5] << 15) + (data[6] << 7) + data[7];
    timestamp /= 45;

    if (pts33Bit) {
      timestamp += 47721858.84;
    } // 2^32 / 90

    return Math.round(timestamp);
  }

  return undefined;
};
 function isFooter  (data, offset) {
  /*
   * The footer is a copy of the header, but with a different identifier
   */
  if (offset + 10 <= data.length) {
    // look for '3DI' identifier
    if (
      data[offset] === 0x33 &&
      data[offset + 1] === 0x44 &&
      data[offset + 2] === 0x49
    ) {
      // check version is within range
      if (data[offset + 3] < 0xff && data[offset + 4] < 0xff) {
        // check size is within range
        if (
          data[offset + 6] < 0x80 &&
          data[offset + 7] < 0x80 &&
          data[offset + 8] < 0x80 &&
          data[offset + 9] < 0x80
        ) {
          return true;
        }
      }
    }
  }

  return false;
};
    function    isHeader   (data, offset)  {
  /*
   * http://id3.org/id3v2.3.0
   * [0]     = 'I'
   * [1]     = 'D'
   * [2]     = '3'
   * [3,4]   = {Version}
   * [5]     = {Flags}
   * [6-9]   = {ID3 Size}
   *
   * An ID3v2 tag can be detected with the following pattern:
   *  $49 44 33 yy yy xx zz zz zz zz
   * Where yy is less than $FF, xx is the 'flags' byte and zz is less than $80
   */
  if (offset + 10 <= data.length) {
    // look for 'ID3' identifier
    if (
      data[offset] === 0x49 &&
      data[offset + 1] === 0x44 &&
      data[offset + 2] === 0x33
    ) {
      // check version is within range
      if (data[offset + 3] < 0xff && data[offset + 4] < 0xff) {
        // check size is within range
        if (
          data[offset + 6] < 0x80 &&
          data[offset + 7] < 0x80 &&
          data[offset + 8] < 0x80 &&
          data[offset + 9] < 0x80
        ) {
          return true;
        }
      }
    }
  }

  return false;
};

       function  readSize  (data, offset) {
  let size = 0;
  size = (data[offset] & 0x7f) << 21;
  size |= (data[offset + 1] & 0x7f) << 14;
  size |= (data[offset + 2] & 0x7f) << 7;
  size |= data[offset + 3] & 0x7f;
  return size;
};

function canParse  (data, offset) {
  return (
    isHeader(data, offset) &&
    readSize(data, offset + 6) + 10 <= data.length - offset
  );
};

function getFrameData  (data) {
  /*
  Frame ID       $xx xx xx xx (four characters)
  Size           $xx xx xx xx
  Flags          $xx xx
  */
  const type = String.fromCharCode(data[0], data[1], data[2], data[3]);
  const size = readSize(data, 4);

  // skip frame id, size, and flags
  const offset = 10;

  return { type, size, data: data.subarray(offset, offset + size) };
};

   function       getID3Frames  (id3Data )  {
  let offset = 0;
   frames = [];

  while (isHeader(id3Data, offset)) {
    const size = readSize(id3Data, offset + 6);
    // skip past ID3 header
    offset += 10;
    const end = offset + size;
    // loop through frames in the ID3 tag
    while (offset + 8 < end) {
      const frameData  = getFrameData(id3Data.subarray(offset));
      const frame = decodeFrame(frameData);
      if (frame) {
        frames.push(frame);
      }

      // skip frame header and frame data
      offset += frameData.size + 10;
    }

    if (isFooter(id3Data, offset)) {
      offset += 10;
    }
  }

  return frames;
};
function getID3Data  (  data, offset)  {
  const front = offset;
  let length = 0;

  while (isHeader(data, offset)) {
    // ID3 header is 10 bytes
    length += 10;

    const size = readSize(data, offset + 6);
    length += size;

    if (isFooter(data, offset + 10)) {
      // ID3 footer is 10 bytes
      length += 10;
    }

    offset += length;
  }

  if (length > 0) {
    return data.subarray(front, front + length);
  }

  return undefined;
};

            var html5Player = new Html5Player();
            var audios=document .getElementsByTagName('video');
            var video=audios[0];
/*var player = videojs(   audio.id);
player.play();
////*/
 var videoSrc = html5Player.settings.url ;// "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8";
 if (Hls.isSupported()) {
    var hls = new Hls();
    hls.onFragParsingMetadata=function (data) {
      data.samples.forEach((sample) => {    console.log(sample.pts);
      var uint8array = new TextEncoder().encode("utf-8");
		var string = new TextDecoder().decode(sample.data);
		console.log(string)
    });

    };
    hls.on(Hls.Events.MEDIA_ATTACHED,function() {
    console.log("video and hls.js are now bound together !");
    hls.loadSource(videoSrc);
    hls.on(Hls.Events.MANIFEST_PARSED, function(event,data) {
     console.log("manifest loaded, found " + data.levels.length + " quality level");
    })
 });
     hls.on(Hls.Events.FRAG_PARSING_METADATA, function (e,data) {
      data.samples.forEach((sample) => {
		var uint8array = new TextEncoder().encode("utf-8");
		var string = new TextDecoder().decode(sample.data);
		frames=getID3Frames(sample.data );
		if(frames)
		for (let j = 0; j < frames.length; j++) {
		  const frame = frames[j];
		  console.log(frame);

		  }
		 console.log(string);
      });

		console.log(this._media.textTracks[0].activeCues[0].value.data);
		this._media.textTracks[0].removeCue( this._media.textTracks[0].activeCues[0]);
		this._media.textTracks[0].cues.clear();
    });


         hls.on(Hls.Events.FRAG_PARSING_USERDATA,  function (e,data) {
            data.samples.forEach((sample) => {
		var uint8array = new TextEncoder().encode("utf-8");
		var string = new TextDecoder().decode(sample.data);
		frames=getID3Frames(sample.data );
		if(frames)
		for (let j = 0; j < frames.length; j++) {
		  const frame = frames[j];
		  console.log(frame);

		  }
		 console.log(string);
      });
    });
    //hls.loadSource(videoSrc);
    hls.attachMedia(video);
    //video.play();
  }
  // HLS.js is not supported on platforms that do not have Media Source
  // Extensions (MSE) enabled.
  //
  // When the browser has built-in HLS support (check using `canPlayType`),
  // we can provide an HLS manifest (i.e. .m3u8 URL) directly to the video
  // element through the `src` property. This is using the built-in support
  // of the plain video element, without using HLS.js.
  //
  // Note: it would be more normal to wait on the 'canplay' event below however
  // on Safari (where you are most likely to find built-in HLS support) the
  // video.src URL must be on the user-driven white-list before a 'canplay'
  // event will be emitted; the last video event that can be reliably
  // listened-for when the URL is not on the white-list is 'loadedmetadata'.
  else if (video.canPlayType('application/vnd.apple.mpegurl')) {
    video.src = videoSrc;
  }
        </script>
    </div>

</body>

</html>
